// Code generated by go-bindata. DO NOT EDIT.
// sources:
// db/migrations/000001_create_department_table.down.sql
// db/migrations/000001_create_department_table.up.sql
// db/migrations/000002_create_student_table.down.sql
// db/migrations/000002_create_student_table.up.sql
// db/migrations/000003_create_staff_table.down.sql
// db/migrations/000003_create_staff_table.up.sql
// db/migrations/000004_create_department_staff_table.down.sql
// db/migrations/000004_create_department_staff_table.up.sql

package migrations


import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}


type asset struct {
	bytes []byte
	info  fileInfoEx
}

type fileInfoEx interface {
	os.FileInfo
	MD5Checksum() string
}

type bindataFileInfo struct {
	name        string
	size        int64
	mode        os.FileMode
	modTime     time.Time
	md5checksum string
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) MD5Checksum() string {
	return fi.md5checksum
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindata000001createdepartmenttableDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x48\x49\x2d\x48\x2c\x2a\xc9\x4d\xcd\x2b\x29\xb6\x06\x04\x00\x00\xff\xff\x01\x7b\x09\x27\x21\x00\x00\x00")

func bindata000001createdepartmenttableDownSqlBytes() ([]byte, error) {
	return bindataRead(
		_bindata000001createdepartmenttableDownSql,
		"000001_create_department_table.down.sql",
	)
}



func bindata000001createdepartmenttableDownSql() (*asset, error) {
	bytes, err := bindata000001createdepartmenttableDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "000001_create_department_table.down.sql",
		size: 33,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1652682575, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindata000001createdepartmenttableUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x0e\x72\x75\x0c\x71\x55\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\xf0\xf3\x0f\x51\x70\x8d\xf0\x0c\x0e\x09\x56\x48\x49\x2d\x48\x2c\x2a\xc9\x4d\xcd\x2b\x29\x56\xd0\xe0\x52\x50\x50\x50\xc8\x4c\x51\x28\x4e\x2d\xca\x4c\xcc\x51\x08\x08\xf2\xf4\x75\x0c\x8a\x54\xf0\x76\x8d\xd4\x01\x4b\xe5\x25\xe6\xa6\x2a\x94\xa4\x56\x94\x70\x69\x5a\x03\x02\x00\x00\xff\xff\x5b\xe7\xfd\x2f\x54\x00\x00\x00")

func bindata000001createdepartmenttableUpSqlBytes() ([]byte, error) {
	return bindataRead(
		_bindata000001createdepartmenttableUpSql,
		"000001_create_department_table.up.sql",
	)
}



func bindata000001createdepartmenttableUpSql() (*asset, error) {
	bytes, err := bindata000001createdepartmenttableUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "000001_create_department_table.up.sql",
		size: 84,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1652682568, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindata000002createstudenttableDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x2e\x29\x4d\x49\xcd\x2b\x29\xb6\x06\x04\x00\x00\xff\xff\x62\xa9\x6d\xa5\x1e\x00\x00\x00")

func bindata000002createstudenttableDownSqlBytes() ([]byte, error) {
	return bindataRead(
		_bindata000002createstudenttableDownSql,
		"000002_create_student_table.down.sql",
	)
}



func bindata000002createstudenttableDownSql() (*asset, error) {
	bytes, err := bindata000002createstudenttableDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "000002_create_student_table.down.sql",
		size: 30,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1652682961, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindata000002createstudenttableUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x4c\x8a\xcd\x0a\x82\x40\x10\xc7\xef\x3e\xc5\xff\xa8\xd0\x1b\x74\x32\x19\x41\x2a\x8b\x75\x0f\x79\x12\x63\x07\x19\x58\xc7\xd8\x9d\xa0\xc7\x0f\xaa\x43\xc7\xdf\x47\xe3\xa8\xf6\x04\x5f\x1f\x4e\x84\xae\x45\x7f\xf1\xa0\x5b\x37\xf8\x01\xd9\x9e\x81\xd5\x32\xca\x02\x00\x24\x20\x73\x92\x39\xe2\xea\xba\x73\xed\x46\x1c\x69\xdc\x7d\x92\xce\x2b\xc3\xf8\x65\x5f\x4c\x5b\x8c\x93\x6e\xb8\xcb\x22\xfa\x73\x81\x1f\x73\xb2\x95\xd5\x26\x09\x10\x35\x5e\x38\xc1\x51\x4b\x8e\xfa\x86\x86\xbf\x21\x97\x12\xaa\xa2\xda\xbf\x03\x00\x00\xff\xff\x57\xf4\xf3\xa7\x9b\x00\x00\x00")

func bindata000002createstudenttableUpSqlBytes() ([]byte, error) {
	return bindataRead(
		_bindata000002createstudenttableUpSql,
		"000002_create_student_table.up.sql",
	)
}



func bindata000002createstudenttableUpSql() (*asset, error) {
	bytes, err := bindata000002createstudenttableUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "000002_create_student_table.up.sql",
		size: 155,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1652682777, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindata000003createstafftableDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x2e\x49\x4c\x4b\x2b\xb6\x06\x04\x00\x00\xff\xff\x0a\xc5\x80\x80\x1c\x00\x00\x00")

func bindata000003createstafftableDownSqlBytes() ([]byte, error) {
	return bindataRead(
		_bindata000003createstafftableDownSql,
		"000003_create_staff_table.down.sql",
	)
}



func bindata000003createstafftableDownSql() (*asset, error) {
	bytes, err := bindata000003createstafftableDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "000003_create_staff_table.down.sql",
		size: 28,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1652683485, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindata000003createstafftableUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x0e\x72\x75\x0c\x71\x55\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\xf0\xf3\x0f\x51\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x2e\x49\x4c\x4b\x2b\x56\xd0\xe0\x52\x50\x50\x50\xc8\x4c\x51\x28\x4e\x2d\xca\x4c\xcc\x51\x08\x08\xf2\xf4\x75\x0c\x8a\x54\xf0\x76\x8d\xd4\x01\x4b\xe5\x25\xe6\xa6\x2a\x94\xa4\x56\x94\x70\x69\x5a\x03\x02\x00\x00\xff\xff\xc0\x62\x5c\xce\x4f\x00\x00\x00")

func bindata000003createstafftableUpSqlBytes() ([]byte, error) {
	return bindataRead(
		_bindata000003createstafftableUpSql,
		"000003_create_staff_table.up.sql",
	)
}



func bindata000003createstafftableUpSql() (*asset, error) {
	bytes, err := bindata000003createstafftableUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "000003_create_staff_table.up.sql",
		size: 79,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1652683473, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindata000004createdepartmentstafftableDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x48\x49\x2d\x48\x2c\x2a\xc9\x4d\xcd\x2b\x29\x8e\x2f\x2e\x49\x4c\x4b\x2b\xb6\x06\x04\x00\x00\xff\xff\xbf\x75\xc5\x30\x28\x00\x00\x00")

func bindata000004createdepartmentstafftableDownSqlBytes() ([]byte, error) {
	return bindataRead(
		_bindata000004createdepartmentstafftableDownSql,
		"000004_create_department_staff_table.down.sql",
	)
}



func bindata000004createdepartmentstafftableDownSql() (*asset, error) {
	bytes, err := bindata000004createdepartmentstafftableDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "000004_create_department_staff_table.down.sql",
		size: 40,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1652683685, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

var _bindata000004createdepartmentstafftableUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x0e\x72\x75\x0c\x71\x55\x28\x49\x4c\xca\x49\x55\xf0\x74\x53\xf0\xf3\x0f\x51\x70\x8d\xf0\x0c\x0e\x09\x56\x48\x49\x2d\x48\x2c\x2a\xc9\x4d\xcd\x2b\x29\x8e\x2f\x2e\x49\x4c\x4b\x2b\xd6\xe0\x52\x80\x80\xcc\x14\x85\x60\xd7\x20\x4f\x47\x1f\x85\x80\x20\x4f\x5f\xc7\xa0\x48\x05\x6f\xd7\x48\x05\x1d\x98\x34\x42\x67\x7c\x66\x8a\x42\x66\x5e\x49\x6a\x7a\x6a\x91\x42\x90\xab\x9b\x6b\x90\xab\x9f\xb3\x2b\x8a\xd1\x1a\x99\x29\x9a\x70\x8d\x60\x6b\x70\xe8\x81\x3a\x21\x33\x45\x93\x4b\xd3\x1a\x10\x00\x00\xff\xff\xb3\x0f\x9c\xe7\xb7\x00\x00\x00")

func bindata000004createdepartmentstafftableUpSqlBytes() ([]byte, error) {
	return bindataRead(
		_bindata000004createdepartmentstafftableUpSql,
		"000004_create_department_staff_table.up.sql",
	)
}



func bindata000004createdepartmentstafftableUpSql() (*asset, error) {
	bytes, err := bindata000004createdepartmentstafftableUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "000004_create_department_staff_table.up.sql",
		size: 183,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1652683699, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}


//
// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
//
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
// nolint: deadcode
//
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

//
// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or could not be loaded.
//
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// AssetNames returns the names of the assets.
// nolint: deadcode
//
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

//
// _bindata is a table, holding each asset generator, mapped to its name.
//
var _bindata = map[string]func() (*asset, error){
	"000001_create_department_table.down.sql":       bindata000001createdepartmenttableDownSql,
	"000001_create_department_table.up.sql":         bindata000001createdepartmenttableUpSql,
	"000002_create_student_table.down.sql":          bindata000002createstudenttableDownSql,
	"000002_create_student_table.up.sql":            bindata000002createstudenttableUpSql,
	"000003_create_staff_table.down.sql":            bindata000003createstafftableDownSql,
	"000003_create_staff_table.up.sql":              bindata000003createstafftableUpSql,
	"000004_create_department_staff_table.down.sql": bindata000004createdepartmentstafftableDownSql,
	"000004_create_department_staff_table.up.sql":   bindata000004createdepartmentstafftableUpSql,
}

//
// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
//
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, &os.PathError{
					Op: "open",
					Path: name,
					Err: os.ErrNotExist,
				}
			}
		}
	}
	if node.Func != nil {
		return nil, &os.PathError{
			Op: "open",
			Path: name,
			Err: os.ErrNotExist,
		}
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}


type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{Func: nil, Children: map[string]*bintree{
	"000001_create_department_table.down.sql": {Func: bindata000001createdepartmenttableDownSql, Children: map[string]*bintree{}},
	"000001_create_department_table.up.sql": {Func: bindata000001createdepartmenttableUpSql, Children: map[string]*bintree{}},
	"000002_create_student_table.down.sql": {Func: bindata000002createstudenttableDownSql, Children: map[string]*bintree{}},
	"000002_create_student_table.up.sql": {Func: bindata000002createstudenttableUpSql, Children: map[string]*bintree{}},
	"000003_create_staff_table.down.sql": {Func: bindata000003createstafftableDownSql, Children: map[string]*bintree{}},
	"000003_create_staff_table.up.sql": {Func: bindata000003createstafftableUpSql, Children: map[string]*bintree{}},
	"000004_create_department_staff_table.down.sql": {Func: bindata000004createdepartmentstafftableDownSql, Children: map[string]*bintree{}},
	"000004_create_department_staff_table.up.sql": {Func: bindata000004createdepartmentstafftableUpSql, Children: map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
