// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package university_management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UniversityManagementServiceClient is the client API for UniversityManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UniversityManagementServiceClient interface {
	GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...grpc.CallOption) (*GetDepartmentResponse, error)
	GetStudents(ctx context.Context, in *GetStudentsRequest, opts ...grpc.CallOption) (*GetStudentsResponse, error)
	GetStudent(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*GetStudentResponse, error)
	GetStaffsForStudent(ctx context.Context, in *GetStaffsForStudentRequest, opts ...grpc.CallOption) (*GetStaffsForStudentResponse, error)
	GetLoginForStudent(ctx context.Context, in *GetRequestForLogin, opts ...grpc.CallOption) (*GetResponseForLogin, error)
	GetLogoutForStudent(ctx context.Context, in *GetRequestForLogout, opts ...grpc.CallOption) (*GetResponseForLogout, error)
	Notify(ctx context.Context, in *GetLoginNotifyRequest, opts ...grpc.CallOption) (*GetLoginNotifyResponse, error)
	StreamAttendanceResponse(ctx context.Context, in *GetRequestForStreamingAttendance, opts ...grpc.CallOption) (UniversityManagementService_StreamAttendanceResponseClient, error)
	GetAttendances(ctx context.Context, in *GetRequestForAttendance, opts ...grpc.CallOption) (*GetResponseForAttendance, error)
}

type universityManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUniversityManagementServiceClient(cc grpc.ClientConnInterface) UniversityManagementServiceClient {
	return &universityManagementServiceClient{cc}
}

func (c *universityManagementServiceClient) GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...grpc.CallOption) (*GetDepartmentResponse, error) {
	out := new(GetDepartmentResponse)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/GetDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) GetStudents(ctx context.Context, in *GetStudentsRequest, opts ...grpc.CallOption) (*GetStudentsResponse, error) {
	out := new(GetStudentsResponse)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/GetStudents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) GetStudent(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*GetStudentResponse, error) {
	out := new(GetStudentResponse)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/GetStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) GetStaffsForStudent(ctx context.Context, in *GetStaffsForStudentRequest, opts ...grpc.CallOption) (*GetStaffsForStudentResponse, error) {
	out := new(GetStaffsForStudentResponse)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/GetStaffsForStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) GetLoginForStudent(ctx context.Context, in *GetRequestForLogin, opts ...grpc.CallOption) (*GetResponseForLogin, error) {
	out := new(GetResponseForLogin)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/GetLoginForStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) GetLogoutForStudent(ctx context.Context, in *GetRequestForLogout, opts ...grpc.CallOption) (*GetResponseForLogout, error) {
	out := new(GetResponseForLogout)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/GetLogoutForStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) Notify(ctx context.Context, in *GetLoginNotifyRequest, opts ...grpc.CallOption) (*GetLoginNotifyResponse, error) {
	out := new(GetLoginNotifyResponse)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) StreamAttendanceResponse(ctx context.Context, in *GetRequestForStreamingAttendance, opts ...grpc.CallOption) (UniversityManagementService_StreamAttendanceResponseClient, error) {
	stream, err := c.cc.NewStream(ctx, &UniversityManagementService_ServiceDesc.Streams[0], "/university_management.UniversityManagementService/StreamAttendanceResponse", opts...)
	if err != nil {
		return nil, err
	}
	x := &universityManagementServiceStreamAttendanceResponseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UniversityManagementService_StreamAttendanceResponseClient interface {
	Recv() (*GetResponseForStreamingAttendance, error)
	grpc.ClientStream
}

type universityManagementServiceStreamAttendanceResponseClient struct {
	grpc.ClientStream
}

func (x *universityManagementServiceStreamAttendanceResponseClient) Recv() (*GetResponseForStreamingAttendance, error) {
	m := new(GetResponseForStreamingAttendance)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *universityManagementServiceClient) GetAttendances(ctx context.Context, in *GetRequestForAttendance, opts ...grpc.CallOption) (*GetResponseForAttendance, error) {
	out := new(GetResponseForAttendance)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/GetAttendances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UniversityManagementServiceServer is the server API for UniversityManagementService service.
// All implementations must embed UnimplementedUniversityManagementServiceServer
// for forward compatibility
type UniversityManagementServiceServer interface {
	GetDepartment(context.Context, *GetDepartmentRequest) (*GetDepartmentResponse, error)
	GetStudents(context.Context, *GetStudentsRequest) (*GetStudentsResponse, error)
	GetStudent(context.Context, *GetStudentRequest) (*GetStudentResponse, error)
	GetStaffsForStudent(context.Context, *GetStaffsForStudentRequest) (*GetStaffsForStudentResponse, error)
	GetLoginForStudent(context.Context, *GetRequestForLogin) (*GetResponseForLogin, error)
	GetLogoutForStudent(context.Context, *GetRequestForLogout) (*GetResponseForLogout, error)
	Notify(context.Context, *GetLoginNotifyRequest) (*GetLoginNotifyResponse, error)
	StreamAttendanceResponse(*GetRequestForStreamingAttendance, UniversityManagementService_StreamAttendanceResponseServer) error
	GetAttendances(context.Context, *GetRequestForAttendance) (*GetResponseForAttendance, error)
	mustEmbedUnimplementedUniversityManagementServiceServer()
}

// UnimplementedUniversityManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUniversityManagementServiceServer struct {
}

func (UnimplementedUniversityManagementServiceServer) GetDepartment(context.Context, *GetDepartmentRequest) (*GetDepartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartment not implemented")
}
func (UnimplementedUniversityManagementServiceServer) GetStudents(context.Context, *GetStudentsRequest) (*GetStudentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudents not implemented")
}
func (UnimplementedUniversityManagementServiceServer) GetStudent(context.Context, *GetStudentRequest) (*GetStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudent not implemented")
}
func (UnimplementedUniversityManagementServiceServer) GetStaffsForStudent(context.Context, *GetStaffsForStudentRequest) (*GetStaffsForStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStaffsForStudent not implemented")
}
func (UnimplementedUniversityManagementServiceServer) GetLoginForStudent(context.Context, *GetRequestForLogin) (*GetResponseForLogin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoginForStudent not implemented")
}
func (UnimplementedUniversityManagementServiceServer) GetLogoutForStudent(context.Context, *GetRequestForLogout) (*GetResponseForLogout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogoutForStudent not implemented")
}
func (UnimplementedUniversityManagementServiceServer) Notify(context.Context, *GetLoginNotifyRequest) (*GetLoginNotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedUniversityManagementServiceServer) StreamAttendanceResponse(*GetRequestForStreamingAttendance, UniversityManagementService_StreamAttendanceResponseServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAttendanceResponse not implemented")
}
func (UnimplementedUniversityManagementServiceServer) GetAttendances(context.Context, *GetRequestForAttendance) (*GetResponseForAttendance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendances not implemented")
}
func (UnimplementedUniversityManagementServiceServer) mustEmbedUnimplementedUniversityManagementServiceServer() {
}

// UnsafeUniversityManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UniversityManagementServiceServer will
// result in compilation errors.
type UnsafeUniversityManagementServiceServer interface {
	mustEmbedUnimplementedUniversityManagementServiceServer()
}

func RegisterUniversityManagementServiceServer(s grpc.ServiceRegistrar, srv UniversityManagementServiceServer) {
	s.RegisterService(&UniversityManagementService_ServiceDesc, srv)
}

func _UniversityManagementService_GetDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).GetDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/GetDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).GetDepartment(ctx, req.(*GetDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_GetStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).GetStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/GetStudents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).GetStudents(ctx, req.(*GetStudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_GetStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).GetStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/GetStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).GetStudent(ctx, req.(*GetStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_GetStaffsForStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStaffsForStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).GetStaffsForStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/GetStaffsForStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).GetStaffsForStudent(ctx, req.(*GetStaffsForStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_GetLoginForStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestForLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).GetLoginForStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/GetLoginForStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).GetLoginForStudent(ctx, req.(*GetRequestForLogin))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_GetLogoutForStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestForLogout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).GetLogoutForStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/GetLogoutForStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).GetLogoutForStudent(ctx, req.(*GetRequestForLogout))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoginNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).Notify(ctx, req.(*GetLoginNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_StreamAttendanceResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequestForStreamingAttendance)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UniversityManagementServiceServer).StreamAttendanceResponse(m, &universityManagementServiceStreamAttendanceResponseServer{stream})
}

type UniversityManagementService_StreamAttendanceResponseServer interface {
	Send(*GetResponseForStreamingAttendance) error
	grpc.ServerStream
}

type universityManagementServiceStreamAttendanceResponseServer struct {
	grpc.ServerStream
}

func (x *universityManagementServiceStreamAttendanceResponseServer) Send(m *GetResponseForStreamingAttendance) error {
	return x.ServerStream.SendMsg(m)
}

func _UniversityManagementService_GetAttendances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestForAttendance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).GetAttendances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/GetAttendances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).GetAttendances(ctx, req.(*GetRequestForAttendance))
	}
	return interceptor(ctx, in, info, handler)
}

// UniversityManagementService_ServiceDesc is the grpc.ServiceDesc for UniversityManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UniversityManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "university_management.UniversityManagementService",
	HandlerType: (*UniversityManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDepartment",
			Handler:    _UniversityManagementService_GetDepartment_Handler,
		},
		{
			MethodName: "GetStudents",
			Handler:    _UniversityManagementService_GetStudents_Handler,
		},
		{
			MethodName: "GetStudent",
			Handler:    _UniversityManagementService_GetStudent_Handler,
		},
		{
			MethodName: "GetStaffsForStudent",
			Handler:    _UniversityManagementService_GetStaffsForStudent_Handler,
		},
		{
			MethodName: "GetLoginForStudent",
			Handler:    _UniversityManagementService_GetLoginForStudent_Handler,
		},
		{
			MethodName: "GetLogoutForStudent",
			Handler:    _UniversityManagementService_GetLogoutForStudent_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _UniversityManagementService_Notify_Handler,
		},
		{
			MethodName: "GetAttendances",
			Handler:    _UniversityManagementService_GetAttendances_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAttendanceResponse",
			Handler:       _UniversityManagementService_StreamAttendanceResponse_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "university-management.proto",
}
